name = "Server Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a741e2a81985f9f1a1e74a0095001ed59b884c9ee607de9ac701ef33a3a2f1a"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
