name = "Server Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cde7c30bd6b4b4c7d28e35430de119fd7aa94065b3a5905f6b1a0328af9a925"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
