name = "Server Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90e77fb95c2703c9d5effa4ffc5c537d7147d474df15f57f2c1ea44769ed3e9b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
