name = "Server Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73fd011e517281f23c9cdf42159a00f292872c3574402b5899af58c2344d4b57"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
