name = "Server Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bec81145fb6da018a7738cdd95183754ea3f0d68f21cc9ee481caa24cc255c7e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
