name = "Server Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7dba6411fcc49315d48a198c4f14e9ab260cbec30202e57f947610d6acd3a20"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
